### PR TITLE
Add Whisper Dictation

### PR DESCRIPTION
**Pull request by NotBrianZach**
**By submitting this pull request, I promise I have read the [contribution guidelines](https://github.com/sindresorhus/awesome-whisper/blob/main/contributing.md) twice and made sure my submission follows it.**

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

### CODE REVIEW

**Comment by sindresorhus** [comment]
> It should have at least 20 stars. - https://github.com/sindresorhus/awesome-whisper/blob/main/contributing.md

**Comment by sindresorhus** [comment]
The readme could also use a clearer intro about what exactly it is and why someone should care. A screenshot could also help.

**Comment by themanyone** [comment]
Sounds good. It's a new creation, so it hasn't received many stars yet. But being a very-simple bash script, it should be easy for people to look over and review, so give it time!

Clear intros are always a challenge. Perhaps ChatGPT can help. Any suggestions?

**Comment by themanyone** [comment]
Whisper dictation and voice typing have 20+ stars now. 
https://github.com/themanyone?tab=repositories

**Pull request closed without merging**
