### PR TITLE
Add Experimental WhisperHallu

### PR DESCRIPTION
**Pull request by EtienneAb3d**
Sound file preprocessing to optimize Whisper transcriptions without hallucinated texts.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please follow the contribution guidelines.

**Comment by EtienneAb3d** [comment]
> Please follow the contribution guidelines.

Please, may I know what I did wrong?

**Comment by EtienneAb3d** [comment]
If this is the problem, I changed it to get only the new category added.

**Comment by sindresorhus** [comment]
I'm going to pass on this. The pull request is not correct, but I also don't think the project is mature enough to include here.

**Pull request closed without merging**
