### PR TITLE
Adds: whisper-standalone-win

### PR DESCRIPTION
**Pull request by Purfview**
**By submitting this pull request, I promise I have read the [contribution guidelines](https://github.com/sindresorhus/awesome-whisper/blob/main/contributing.md) twice and made sure my submission follows it.**

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

### CODE REVIEW

**Comment by sindresorhus** [comment]
The "CLI" section would be more appropriate.

**Comment by Purfview** [comment]
It says "CLI Tools", but it's not a tool.

**Review by Purfview — COMMENTED** [review]
moved to CLI

**Comment by sindresorhus** [comment]
But it's not an app either.

**Pull request merged**
