### PR TITLE
Add Vibe

### PR DESCRIPTION
**Pull request by thewh1teagle**
**By submitting this pull request, I promise I have read the [contribution guidelines](https://github.com/sindresorhus/awesome-whisper/blob/main/contributing.md) twice and made sure my submission follows it.**

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

### CODE REVIEW

**Comment by sindresorhus** [comment]
Right now, it looks more like a website than an actual app. I recommend making it look like a proper app.

**Comment by thewh1teagle** [comment]
@sindresorhus
Thanks for the input. The GitHub repo is live, and the link I added is to the repo itself with downloads available in the first section of the README. It's interesting that you see it more as a website rather than an app; could you elaborate? If there are other reasons for holding off on merging, I'm all ears.

**Comment by thewh1teagle** [comment]
@sindresorhus 
I've updated the app and the website. Does it make sense now? If not, please let me know. If you don't see any chance please close the pr. Thanks

**Comment by sindresorhus** [comment]
I'm going to pass on this. Looking at the screenshots, it still looks like a website and not an app. A proper app has a toolbar, more balanced components placements, etc.

**Pull request closed without merging**
